### ISSUE TITLE
Maybe update to Node 4.8.2 or determine Node version from Meteor version?

### ISSUE THREAD

**Issue by aldeed** [chriswessels/meteor-tupperware#32]
I got errors sending emails with Meteor `email` pkg when deploying an app that I just updated. It complains about use of `Buffer.from` in `node4mailer`. This is because it got auto-updated to 1.2.1 of email pkg (see https://github.com/meteor/meteor/pull/8609). I don't think that should have been a patch version bump of the email pkg, but too late now. But I believe using newer Node will fix because I don't see the issue with `meteor run`, so maybe a good fix would be to rebuild the tupperware image using Node 4.8.2?

FYI @edemaine

(The way I've fixed for now is by pinning `email@=1.2.0`)

**Comment by edemaine** [comment]
I wouldn't recommend using `email@1.2.0` -- it's buggy for long-lived connections, which is why I numbered 1.2.1 a (quickly thereafter) bugfix release (though I could see an argument for 1.3.0).

Which version of Node is currently in `meteor-tupperware`?  I thought Meteor included Node 4.8.1 since Meteor 1.4.4, but I guess other systems can diverge from this.

**Comment by aldeed** [comment]
@edemaine Meteor has been including later versions of Node for the past several releases, but that is only when doing `meteor run`. Tupperware does a `meteor build` in the Docker container and installs an older Node that is used when running the built Node app. So regardless of deployment method, anyone who deploys on a system running older Node will encounter this issue. I think the updates to email pkg were good and correct, but it should have been 2.0 due to the Node dependency change. There are probably some older versions of Meteor which depend on email 1.x but come bundled with an earlier Node and will crash even on `meteor run` after people `meteor update email`.

Ideally I think it would be nice if tupperware had a Meteor version -> Node version map and installed the proper version ONBUILD after checking the Meteor version.

And yes, my app is crashing with `email@1.2.0` due to the eventual connection failure, but it at least sends the email prior to that. With 1.2.1 it crashed while trying to send the email.

**Comment by edemaine** [comment]
@aldeed Thanks for the explanation!  (I'm obviously not familiar with `meteor-tupperware`.)  Another alternative would be to modify `node4mailer` to work on earlier Node versions.  Can you tell from the error messages what the issue is?  If it's small, I could modify `node4mailer` and the `email` package to avoid the issue.  Also, if you could tell me which version of Node you're using, I can do my own testing.

**Comment by aldeed** [comment]
@edemaine Node 4.4.7. It is `TypeError: this is not a typed array` error on this line: https://github.com/edemaine/node4mailer/blob/master/lib/mime-node/last-newline.js#L28

There may be other errors beyond that if you fix that one. I didn't look too closely at what that code is doing, but I did find this SO related to the error: http://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha

**Comment by edemaine** [comment]
@aldeed OK, it wasn't too bad -- Node 4.4.7 supports `Buffer`, but lacks some of the newer syntax (specifically, `Buffer.from` and `Buffer.alloc`, which can be simulated via `new Buffer`).  I've released `node4mailer@4.0.3` which tests well on Node 4.4.7.  If it's easy to test this, that would be helpful.  Otherwise we'll need to wait for Meteor to publish a new version of `email` that depends on this version of `node4mailer`.

(This said, I'd still recommend that `meteor-tupperware` upgrade its Node version, as Meteor technically requires it.)

**Comment by aldeed** [comment]
@edemaine Thanks! Maybe I will pull in updated email pkg as a local pkg if I get some time.

@chriswessels Leaving this issue open as a request that should still be done.

**Comment by edemaine** [comment]
@aldeed You can download [this email package](https://github.com/edemaine/meteor/tree/devel/packages/email) and put it in a local package (i.e., under `packages/email`) and it should let you test.  Thanks!

**Comment by jshimko** [comment]
cc: @aldeed 

For what it's worth, my base image ([jshimko/meteor-launchpad](https://github.com/jshimko/meteor-launchpad)) is always kept up to date with the latest Node 4.x and it optionally lets you override the Node version at build time if you want (using Docker's `--build-arg` flags.

As for Nodemailer, the maintainer officially blew a gasket and [quit the project](http://nodemailer.com/status/) recently, so we at Reaction Commerce [forked it](https://github.com/reactioncommerce/nodemailer) and will be maintaining it moving forward. 
 I also fixed the requirement of Node 6.x.  It now gets compiled with Babel before publishing to NPM, so it's all ES5 code and should run on any version of Node from 4 up.

```sh
npm i -S @reactioncommerce/nodemailer
```

Also, pretty sure this project is [no longer maintained](https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/4).

**Comment by edemaine** [comment]
Cool to hear, @jshimko .  I guess my [node4mailer package](https://www.npmjs.com/package/node4mailer), which is used in the current Meteor `email` package, isn't necessary anymore.  If you make substantial updates (features or bug fixes other than Node 4 compatibility), Meteor should probably switch over to `reactioncommerce/nodemailer` -- please let me know.

**Comment by jshimko** [comment]
Will do.  Thanks for the heads up @edemaine.

**Comment by chriswessels** [comment]
Hi @aldeed, unfortunately I'm no longer maintaining this package. If you're looking for an alternative, I'd highly recommend https://github.com/jshimko/meteor-launchpad. Thanks for using tupperware.
